name: gale on gha

on: workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - run: make mage.lint
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - run: make mage.test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - run: make mage.build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
