name: gale on self-hosted runner

on: workflow_dispatch

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential

      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - run: make mage.lint
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential

      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - run: make mage.test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential

      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - run: make mage.build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
